'use strict';
function SampleHouse() {
  let that = this;
  that.metaPacks = [
    {
      name: 'base mvp song melodies',
      metas: [
        {
          url: '/audio/teplite-mvp-chapter-a-01.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-02.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-03.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-04.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-05.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-06.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-07.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-08.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-09.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },


        {
          url: '/audio/teplite-mvp-chapter-a-10.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-11.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-12.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-13.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-14.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-15.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-16.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-17.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-18.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-19.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },


        {
          url: '/audio/teplite-mvp-chapter-a-20.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-21.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-22.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-23.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-24.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-25.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-26.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-27.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-28.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-29.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },


        {
          url: '/audio/teplite-mvp-chapter-a-30.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-31.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-32.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-33.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-34.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-35.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-36.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-37.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-38.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-39.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },



        {
          url: '/audio/teplite-mvp-chapter-a-40.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-41.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-42.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-43.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-44.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-45.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-46.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-47.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-48.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },
        {
          url: '/audio/teplite-mvp-chapter-a-49.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },

        {
          url: '/audio/teplite-mvp-chapter-a-50.mp3',
          startAtime: 0,
          endAtime: 16 / teplite.optionset.bpm * 60,
          drumRatio: 1,
          fxRatio: 1,
          melodyRatio: 1,
          voiceRatio: 1,
          quietRatio: 1,
          loudRatio: 1,
        },




      ]
    },
    {
      name: 'base mvp song metros',
      metas: [
        {
          url: '/audio/teplite-mvp-chapter-a-hats-4.mp3',
          startAtime: 0,
          endAtime: 2 / teplite.optionset.bpm * 60,
          isLoop: true,
        },

      ]
    }
  ]
}

module.exports = SampleHouse;